// <auto-generated />
using System;
using Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Domain.Migrations
{
    [DbContext(typeof(Chempedb_context))]
    [Migration("20221104060225_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Chempe.Acceptance", b =>
                {
                    b.Property<int>("Acceptance_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datetime_acceptance")
                        .HasColumnType("datetime2");

                    b.Property<int?>("User_client_ID")
                        .HasColumnType("int");

                    b.HasKey("Acceptance_ID");

                    b.HasIndex("User_client_ID");

                    b.ToTable("Acceptance");
                });

            modelBuilder.Entity("Domain.Chempe.Approval", b =>
                {
                    b.Property<int>("Approval_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datetime_approval")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Loan_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Primary_coupon_rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("User_chempe_ID")
                        .HasColumnType("int");

                    b.HasKey("Approval_ID");

                    b.HasIndex("User_chempe_ID");

                    b.ToTable("Approval");
                });

            modelBuilder.Entity("Domain.Chempe.Assignment", b =>
                {
                    b.Property<int>("Assignment_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datetime_assignment")
                        .HasColumnType("datetime2");

                    b.Property<int?>("User_investor_ID")
                        .HasColumnType("int");

                    b.HasKey("Assignment_ID");

                    b.HasIndex("User_investor_ID");

                    b.ToTable("Assignment");
                });

            modelBuilder.Entity("Domain.Chempe.List_goods_type", b =>
                {
                    b.Property<int>("List_goods_type_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("List_goods_type_ID");

                    b.ToTable("List_goods_type");
                });

            modelBuilder.Entity("Domain.Chempe.Person", b =>
                {
                    b.Property<int>("Person_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Date_born")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Full_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("User_chempe_ID")
                        .HasColumnType("int");

                    b.Property<int?>("User_client_ID")
                        .HasColumnType("int");

                    b.Property<int?>("User_client_ID1")
                        .HasColumnType("int");

                    b.Property<int?>("User_investor_ID")
                        .HasColumnType("int");

                    b.HasKey("Person_ID");

                    b.HasIndex("User_chempe_ID");

                    b.HasIndex("User_client_ID");

                    b.HasIndex("User_client_ID1");

                    b.HasIndex("User_investor_ID");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Domain.Chempe.Photo", b =>
                {
                    b.Property<int>("Photo_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datetime_upload")
                        .HasColumnType("datetime2");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Photo_ID");

                    b.ToTable("Photo");
                });

            modelBuilder.Entity("Domain.Chempe.Pledge", b =>
                {
                    b.Property<int>("Pledge_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Approval_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Assignment_ID")
                        .HasColumnType("int");

                    b.Property<int>("Loan_term")
                        .HasColumnType("int");

                    b.Property<int?>("Pledge_state_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Request_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Warrant_ID")
                        .HasColumnType("int");

                    b.HasKey("Pledge_ID");

                    b.HasIndex("Approval_ID");

                    b.HasIndex("Assignment_ID");

                    b.HasIndex("Pledge_state_ID");

                    b.HasIndex("Request_ID");

                    b.HasIndex("Warrant_ID");

                    b.ToTable("Pledge");
                });

            modelBuilder.Entity("Domain.Chempe.Pledge_state", b =>
                {
                    b.Property<int>("Pledge_state_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datetime_lastUpdate")
                        .HasColumnType("datetime2");

                    b.HasKey("Pledge_state_ID");

                    b.ToTable("Pledge_state");
                });

            modelBuilder.Entity("Domain.Chempe.Request", b =>
                {
                    b.Property<int>("Request_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datetime_request")
                        .HasColumnType("datetime2");

                    b.Property<int?>("User_client_ID")
                        .HasColumnType("int");

                    b.HasKey("Request_ID");

                    b.HasIndex("User_client_ID");

                    b.ToTable("Request");
                });

            modelBuilder.Entity("Domain.Chempe.User_chempe", b =>
                {
                    b.Property<int>("User_chempe_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("User_setting_ID")
                        .HasColumnType("int");

                    b.HasKey("User_chempe_ID");

                    b.HasIndex("User_setting_ID");

                    b.ToTable("User_chempe");
                });

            modelBuilder.Entity("Domain.Chempe.User_client", b =>
                {
                    b.Property<int>("User_client_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("User_setting_ID")
                        .HasColumnType("int");

                    b.HasKey("User_client_ID");

                    b.HasIndex("User_setting_ID")
                        .IsUnique()
                        .HasFilter("[User_setting_ID] IS NOT NULL");

                    b.ToTable("User_client");
                });

            modelBuilder.Entity("Domain.Chempe.User_investor", b =>
                {
                    b.Property<int>("User_investor_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image_Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("User_setting_ID")
                        .HasColumnType("int");

                    b.HasKey("User_investor_ID");

                    b.HasIndex("User_setting_ID")
                        .IsUnique()
                        .HasFilter("[User_setting_ID] IS NOT NULL");

                    b.ToTable("User_investor");
                });

            modelBuilder.Entity("Domain.Chempe.User_setting", b =>
                {
                    b.Property<int>("User_setting_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_setting_ID");

                    b.ToTable("User_setting");
                });

            modelBuilder.Entity("Domain.Chempe.Warrant", b =>
                {
                    b.Property<int>("Warrant_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Current_fair_value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Datetime_purchase")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Goods_typeList_goods_type_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("Purchase_import")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Warrant_ID");

                    b.HasIndex("Goods_typeList_goods_type_ID");

                    b.ToTable("Warrant");
                });

            modelBuilder.Entity("Domain.Chempe.Acceptance", b =>
                {
                    b.HasOne("Domain.Chempe.User_client", "User_acceptance")
                        .WithMany()
                        .HasForeignKey("User_client_ID");

                    b.Navigation("User_acceptance");
                });

            modelBuilder.Entity("Domain.Chempe.Approval", b =>
                {
                    b.HasOne("Domain.Chempe.User_chempe", "User_approval")
                        .WithMany()
                        .HasForeignKey("User_chempe_ID");

                    b.Navigation("User_approval");
                });

            modelBuilder.Entity("Domain.Chempe.Assignment", b =>
                {
                    b.HasOne("Domain.Chempe.User_investor", "User_assignment")
                        .WithMany()
                        .HasForeignKey("User_investor_ID");

                    b.Navigation("User_assignment");
                });

            modelBuilder.Entity("Domain.Chempe.Person", b =>
                {
                    b.HasOne("Domain.Chempe.User_chempe", "User_chempe")
                        .WithMany()
                        .HasForeignKey("User_chempe_ID");

                    b.HasOne("Domain.Chempe.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("User_client_ID");

                    b.HasOne("Domain.Chempe.User_client", "User_client")
                        .WithMany()
                        .HasForeignKey("User_client_ID1");

                    b.HasOne("Domain.Chempe.User_investor", "User_investor")
                        .WithMany()
                        .HasForeignKey("User_investor_ID");

                    b.Navigation("Photo");

                    b.Navigation("User_chempe");

                    b.Navigation("User_client");

                    b.Navigation("User_investor");
                });

            modelBuilder.Entity("Domain.Chempe.Pledge", b =>
                {
                    b.HasOne("Domain.Chempe.Approval", "Approval")
                        .WithMany()
                        .HasForeignKey("Approval_ID");

                    b.HasOne("Domain.Chempe.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("Assignment_ID");

                    b.HasOne("Domain.Chempe.Pledge_state", "Pledge_state")
                        .WithMany()
                        .HasForeignKey("Pledge_state_ID");

                    b.HasOne("Domain.Chempe.Request", "Request")
                        .WithMany()
                        .HasForeignKey("Request_ID");

                    b.HasOne("Domain.Chempe.Warrant", "Warrant")
                        .WithMany()
                        .HasForeignKey("Warrant_ID");

                    b.Navigation("Approval");

                    b.Navigation("Assignment");

                    b.Navigation("Pledge_state");

                    b.Navigation("Request");

                    b.Navigation("Warrant");
                });

            modelBuilder.Entity("Domain.Chempe.Request", b =>
                {
                    b.HasOne("Domain.Chempe.User_client", "User_request")
                        .WithMany()
                        .HasForeignKey("User_client_ID");

                    b.Navigation("User_request");
                });

            modelBuilder.Entity("Domain.Chempe.User_chempe", b =>
                {
                    b.HasOne("Domain.Chempe.User_setting", "User_setting")
                        .WithMany()
                        .HasForeignKey("User_setting_ID");

                    b.Navigation("User_setting");
                });

            modelBuilder.Entity("Domain.Chempe.User_client", b =>
                {
                    b.HasOne("Domain.Chempe.User_setting", "User_setting")
                        .WithOne("User_client")
                        .HasForeignKey("Domain.Chempe.User_client", "User_setting_ID");

                    b.Navigation("User_setting");
                });

            modelBuilder.Entity("Domain.Chempe.User_investor", b =>
                {
                    b.HasOne("Domain.Chempe.User_setting", "User_setting")
                        .WithOne("User_investor")
                        .HasForeignKey("Domain.Chempe.User_investor", "User_setting_ID");

                    b.Navigation("User_setting");
                });

            modelBuilder.Entity("Domain.Chempe.Warrant", b =>
                {
                    b.HasOne("Domain.Chempe.List_goods_type", "Goods_type")
                        .WithMany()
                        .HasForeignKey("Goods_typeList_goods_type_ID");

                    b.Navigation("Goods_type");
                });

            modelBuilder.Entity("Domain.Chempe.User_setting", b =>
                {
                    b.Navigation("User_client");

                    b.Navigation("User_investor");
                });
#pragma warning restore 612, 618
        }
    }
}
